-- CREAR TABLA NOMBRE CAJERO


DROP TABLE IF EXISTS CAJERO;

CREATE TABLE CAJERO(
    MONEDA FLOAT PRIMARY KEY,
    CANTIDAD INTEGER CHECK (CANTIDAD >= 0)
);

DECLARE

    TYPE TABLA IS TABLE OF NUMBER INDEX BY BINARY_INTEGER;
    TB TABLA;


BEGIN
    tb(1) := 5;
    tb(2) := 2;
    tb(3) := 1;
    FOR I IN REVERSE -2..2 LOOP
        FOR J IN 1..3 LOOP
            INSERT INTO CAJERO VALUES(POWER(10, I) * TB(J), 100);
        END LOOP;
    END LOOP;
END;

SELECT * FROM CAJERO;